apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: nginx	  
